In [67]:
import string
from typing import List
import numpy as np

In [76]:


def is_prime(x: int) -> bool:
    if x < 2 or x != 2 and x % 2 == 0 or x != 3 and x % 3 == 0:
        return False
    for d in range(5, 1 + int(x ** 0.5), 6):
        if x % d == 0 or x % (d + 2) == 0:
            return False
    return True

def run():
    print([x for x in range(100) if is_prime(x)])

run()

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [69]:
def read_file(path: str) -> str:
    return open(path, "r").read()


def order_words(text: str) -> List[str]:
    text_words = [word.strip(string.punctuation) for word in text.split()]
    text_words.sort(key=lambda v: v.upper())
    return text_words


print(order_words(read_file("text.txt")))

['ad', 'ad', 'adipisci', 'adolescens', 'alienum', 'aliquid', 'an', 'an', 'an', 'appareat', 'assentior', 'assentior', 'at', 'at', 'at', 'audiam', 'brute', 'complectitur', 'concludaturque', 'congue', 'consectetuer', 'consequat', 'constituto', 'corrumpit', 'cu', 'cu', 'cu', 'cum', 'decore', 'Deleniti', 'disputando', 'dolore', 'duo', 'ea', 'ea', 'ea', 'eloquentiam', 'Eripuit', 'error', 'erroribus', 'est', 'Est', 'est', 'eu', 'eu', 'euismod', 'eum', 'ex', 'ex', 'ex', 'ex', 'facete', 'fugit', 'gloriatur', 'has', 'his', 'id', 'Id', 'instructior', 'iriure', 'Ius', 'labore', 'labores', 'laoreet', 'libris', 'lucilius', 'mea', 'mea', 'mea', 'mea', 'mea', 'mei', 'mei', 'melius', 'molestie', 'molestie', 'mollis', 'Nam', 'nam', 'ne', 'ne', 'nominati', 'nominavi', 'nominavi', 'nostro', 'nostro', 'nostrum', 'nusquam', 'nusquam', 'omittantur', 'omnium', 'patrioque', 'per', 'per', 'pertinacia', 'ponderum', 'possit', 'principes', 'pro', 'propriae', 'purto', 'qualisque', 'Quem', 'qui', 'Qui', 'quod', 'rat

In [70]:
def get_matrix_from_file(path: str) -> List[List[int]]:
    return eval(open(path, "r").read())

a_nn: List[List[int]] = get_matrix_from_file("matrix.txt")
b_nn: List[List[int]] = get_matrix_from_file("vector.txt")

In [71]:
def dot(array_1: List[List[int]], array_2: List[List[int]]) -> List[List[int]]:
    array_3 = [
        [0],
        [0],
        [0]
    ]
    for i in range(len(array_1)):
        for j in range(len(array_2[0])):
            for k in range(len(array_2)):
                array_3[i][j] += array_1[i][k] * array_2[k][j]
    return array_3

dot(a_nn, b_nn)

[[-27], [-87], [-147]]

In [72]:

def run():
    np_a = np.array(a_nn)
    np_b = np.array(b_nn)

    print(np_a[:2, -2:])
    print(np_b[-2:])

run()

[[ 3  4]
 [13 14]]
[[  7]
 [-10]]


In [73]:
def run():
    v_1 = np.random.rand(3)
    v_2 = np.random.rand(3)
    s1 = v_1.sum()
    s2 = v_2.sum()
    print("a)")
    print("v1:", v_1)
    print("sum(v1) = ", s1)
    print("v2:", v_2)
    print("sum(v2) = ", s2)
    if s1 > s2:
        print("v1 > v2")
    elif s2 > s1:
        print("v1 < v2")
    else:
        print("v1 = v2")
    vector_sum = np.add(v_1, v_2)
    cross_prod = np.cross(v_1, v_2)
    vector_prod = np.outer(v_1, v_2)
    scalar_prod = np.dot(v_1, v_2)
    print("b)")
    print("Vectors' sum = ", vector_sum)
    print("The cross product of 2 vectors = ", cross_prod)
    print("The outer product of 2 vectors = ", vector_prod)
    print("The scalar product of 2 vectors = ", scalar_prod)
    print("c)")
    print(np.sqrt(v_1))

run()

a)
v1: [0.84011906 0.47516091 0.40237761]
sum(v1) =  1.7176575869685453
v2: [0.07706536 0.84658671 0.76670348]
sum(v2) =  1.69035554184784
v1 > v2
b)
Vectors' sum =  [0.91718442 1.32174762 1.16908109]
The cross product of 2 vectors =  [ 0.02365998 -0.61311283  0.67461518]
The outer product of 2 vectors =  [[0.06474408 0.71123363 0.6441222 ]
 [0.03661845 0.40226491 0.36430752]
 [0.03100938 0.34064754 0.30850432]]
The scalar product of 2 vectors =  0.7755133043121286
c)
[0.91658009 0.68931917 0.63433242]


In [74]:
def run():
    matrix_1 = np.random.rand(5, 5)
    print("a)")
    print("m: ")
    print(matrix_1)
    print("m.T")
    print(matrix_1.T)

    print("\nb)")
    print("m^-1: ")
    print(np.linalg.inv(matrix_1))
    print("det(m)")
    print(np.linalg.det(matrix_1))

run()

a)
m: 
[[0.21747479 0.2840497  0.24233731 0.16906133 0.67281669]
 [0.63583184 0.59128776 0.01030866 0.64079514 0.18300921]
 [0.18784309 0.57444476 0.93803873 0.28036324 0.45077407]
 [0.67123399 0.59511099 0.72573923 0.75511247 0.05070229]
 [0.89728842 0.78737481 0.10071753 0.19098503 0.7583162 ]]
m.T
[[0.21747479 0.63583184 0.18784309 0.67123399 0.89728842]
 [0.2840497  0.59128776 0.57444476 0.59511099 0.78737481]
 [0.24233731 0.01030866 0.93803873 0.72573923 0.10071753]
 [0.16906133 0.64079514 0.28036324 0.75511247 0.19098503]
 [0.67281669 0.18300921 0.45077407 0.05070229 0.7583162 ]]

b)
m^-1: 
[[ 0.2704233  -2.41119157 -2.04316071  2.39096818  1.39664861]
 [-2.74598604  2.78690477  2.88229952 -2.88184785  0.24312601]
 [ 0.12278103 -1.56458544  0.08102012  1.23527213  0.13789964]
 [ 1.66503895  1.4642298  -0.50238464  0.28784821 -1.55128709]
 [ 2.09557545 -0.20159023 -0.45938328 -0.07342836 -0.21395325]]
det(m)
-0.0687494630318019


In [75]:
def run():
    matrix = np.random.rand(5, 5)
    vector = np.random.rand(5)
    print("Matrix:\n", matrix)
    print("Vector:\n", vector)
    print("Scalar product = ", np.dot(matrix, vector))
    print("Scalar product = ", matrix @ vector)

run()

Matrix:
 [[0.52750218 0.33841469 0.6273005  0.87349917 0.65402453]
 [0.78632264 0.11219156 0.82254783 0.46121034 0.07194735]
 [0.22967939 0.95728981 0.41125115 0.27743398 0.9585705 ]
 [0.68569729 0.5141386  0.36056613 0.22932298 0.93794761]
 [0.40399247 0.00651317 0.46431403 0.57270867 0.337442  ]]
Vector:
 [0.50381888 0.28167952 0.7313573  0.57404168 0.85960552]
Scalar product =  [1.88349887 1.3559429  1.66938844 1.69189812 1.16377876]
Scalar product =  [1.88349887 1.3559429  1.66938844 1.69189812 1.16377876]
